#!/bin/sh
set +x
get_master_ip() {
   for ii in $(cat /proc/cmdline); do
      xcat_server_ip=$(echo $ii | awk -F= '{if($1=="XCAT") print $2}' | awk -F: '{print $1}')
      [ -n "$xcat_server_ip" ] && break
   done
   [ -f /opt/xcat/xcatinfo ] &&  . /opt/xcat/xcatinfo
   [ ! -n "$xcat_server_ip" -a -n "$XCATSERVER" ] &&  xcat_server_ip=$XCATSERVER
   [ ! -n "$xcat_server_ip" -a -f /xcatpost/mypostscript ] && xcat_server_ip=$(awk -F= '{if("^MASTER_IP" == $1) print $2}' /xcatpost/mypostscript)
   [ -n "$xcat_server_ip" ] && echo $xcat_server_ip
}

update_boot_state() {
   xcat_server_ip=$(get_master_ip)
#   [ -f /xcatpost/mypostscript ] && boot_mode=$(awk -F= '{if("NODESETSTATE" == $1) print $2}' /xcatpost/mypostscript)
#   [ "$boot_mode" == "netboot" ] && boot_state="netbooted" || boot_state="booted"
   boot_state="booted"
   while [ 1 ] ; do
       [ -n "$xcat_server_ip" ] && \
       /xcatpost/updateflag.awk $xcat_server_ip 3002 "installstatus ${boot_state}" || \
       xcat_server_ip=$(get_master_ip)
       sleep 400
   done
}

update_boot_state &

