#!/bin/bash
#

get_master_ip() {
   for ii in $(cat /proc/cmdline); do
      xcat_server_ip=$(echo $ii | awk -F= '{if($1=="XCAT") print $2}' | awk -F: '{print $1}')
      [ -n "$xcat_server_ip" ] && break
   done
   [ -f /opt/xcat/xcatinfo ] &&  . /opt/xcat/xcatinfo
   [ ! -n "$xcat_server_ip" -a -n "$XCATSERVER" ] &&  xcat_server_ip=$XCATSERVER
   [ ! -n "$xcat_server_ip" -a -f /xcatpost/mypostscript ] && xcat_server_ip=$(awk -F= '{if("^MASTER_IP" == $1) print $2}' /xcatpost/mypostscript)
   [ -n "$xcat_server_ip" ] && echo $xcat_server_ip
}

_scp() {
   local ip file
   ip=$1
   file=$2
   opt=$3
   [ ! -n "$ip" -o ! -n "$file" ] && return 1
   if [ "$opt" == "-r" ]; then
      [ -d $file ] || scp -r $ip:$file $file
   else
      [ -f $file ] || scp $ip:$file $file
   fi
}

hostname $(hostname -s)
if id slurm >& /dev/null; then
  if [ ! -f /etc/slurm/slurm.key ]; then
     mgt_ip=$(get_master_ip)
     if [ -n "$mgt_ip" ]; then
         if ssh ${mgt_ip} "[ -f /etc/slurm/slurm.key ] || exit 1"; then
            _scp "${mgt_ip}" "/etc/slurm" "-r"
            _scp "${mgt_ip}" "/lib/systemd/system/slurmd.service"
            _scp "${mgt_ip}" "/etc/sysconfig/slurm"
            _scp "${mgt_ip}" "/etc/profile.d/slurm.sh"
         fi
     fi
  fi
  [ ! -f /etc/slurm/slurm.key -o ! -f /etc/slurm/slurm.conf ] && exit
  [ ! -f /lib/systemd/system/slurmd.service -a ! -f /etc/init.d/slurm ] && exit 
  sleep 2
  systemctl daemon-reload

  [ -d /var/spool/slurm ] || mkdir -p /var/spool/slurm
  chown slurm:slurm /var/spool/slurm
  systemctl start slurmd
  sleep 7
  scontrol update nodename=$(hostname -s) state=idle
fi
