#!/bin/sh
# KG Feature for booting procedure

if [ -d /xcatpost/kxcat_boot.d ]; then
   cd /xcatpost/kxcat_boot.d
   for ii in $(ls | sort -n); do
      echo
      echo " ** Run /xcatpost/kxcat_boot.d/$ii at $(date)"
      sh -x /xcatpost/kxcat_boot.d/$ii 
   done >> /tmp/kxcat_boot.log
fi

for ii in $(cat /proc/cmdline); do
   xcat_server_ip=$(echo $ii | awk -F= '{if($1=="XCAT") print $2}' | awk -F: '{print $1}')
   [ -n "$xcat_server_ip" ] && break
done
[ -d /global ] || mkdir -p /global
[ -f /opt/xcat/xcatinfo ] &&  . /opt/xcat/xcatinfo 
if [ ! -n "$xcat_server_ip" && -n "$XCATSERVER" ]; then
    xcat_server_ip=$XCATSERVER
else
    xcat_server_ip=$(awk -F= '{if("^MASTER_IP" == $1) print $2}' /xcatpost/mypostscript)
fi
if [ -n "$xcat_server_ip" ]; then
  if ping -c 2 $xcat_server_ip >& /dev/null; then
     mount -o vers=3,nolock $xcat_server_ip:/global /global
  else
     echo "Can't ping to $xcat_server_ip"
  fi
else
  echo "Can't find Master or XCATSERVER IP"
fi

if [ -f /xcatpost/mypostscript ]; then
   group=$(awk -F= '{if($1=="GROUP") print $2}' /xcatpost/mypostscript | sed "s/'//g" | sed "s/all,nodes//g" | sed "s/,//g")
fi
if [ -d /global/kxcat_boot.d ]; then
   if [ -n "$group" -a -d "/global/kxcat_boot.d/$group" ]; then
      group_shell=($(ls /global/kxcat_boot.d/$group | sort -n))
      for ((ii=0; ii<${#group_shell[*]}; ii++)); do
         if [ -f /global/kxcat_boot.d/${group}/${group_shell[$ii]} ]; then
            echo 
            echo " ** Run $group/${group_shell[$ii]} at $(date)"
            sh -x /global/kxcat_boot.d/${group}/${group_shell[$ii]}
         fi
      done >> /tmp/kxcat_boot.log
   fi
   if [ -d /global/kxcat_boot.d/global ]; then
      global_shell=($(ls /global/kxcat_boot.d/global | sort -n))
      for ((ii=0;ii<${#group_shell[*]};ii++));do
          for ((zz=0;zz<${#global_shell[*]};zz++)); do
              [ "${group_shell[$ii]}" == "${global_shell[$zz]}" ] && unset global_shell[$zz]
          done
      done
      for ((ii=0;ii<${#global_shell[*]};ii++)); do
         if [ -f /global/kxcat_boot.d/global/${global_shell[$ii]} ]; then
           echo 
           echo " ** Run global/${global_shell[$ii]} at $(date)"
           sh -x /global/kxcat_boot.d/global/${global_shell[$ii]}
         fi
      done >> /tmp/kxcat_boot.log
   fi
fi
