#!/bin/bash 
PATH=/bin:/sbin:/usr/bin:/usr/sbin

if [ "$(uname -s|tr 'A-Z' 'a-z')" = "linux" ];then
   str_dir_name=`dirname $0`
   . $str_dir_name/xcatlib.sh
fi

echo "Start remote shell config" > /tmp/remoteshell.log
rm -f /etc/ssh/ssh_known_hosts*
sleep 5
for ii in $(seq 0 10); do
   [ -f /opt/xcat/xcatinfo ] && break
   echo wait /opt/xcat/xcatinfo >> /tmp/remoteshell.log
   sleep 3
done
for ii in $(seq 0 10); do
   [ -f /xcatpost/mypostscript ] && break
   echo wait /xcatpost/mypostscript >> /tmp/remoteshell.log
   sleep 3
done
. /opt/xcat/xcatinfo
MONSERVER=$(awk -F= '{if($1=="MONSERVER") print $2}' /xcatpost/mypostscript | sed "s/'//g")
echo "Check /opt/xcat/xcatinstallpost file" >> /tmp/remoteshell.log
if [ -f /opt/xcat/xcatinstallpost ]; then
   echo "Found /opt/xcat/xcatinstallpost file" >> /tmp/remoteshell.log
   echo "Update .ssh in root account" >> /tmp/remoteshell.log
   [ -d /root/.ssh ] || mkdir -p /root/.ssh
   chmod 700 /root/.ssh
   if [ -f /xcatpost/hostkeys/authorized_keys ]; then
      cp -a /xcatpost/hostkeys/authorized_keys /root/.ssh
   else
      for ii in $(seq 0 20); do
         echo "*** Try($ii) download postscripts" >> /tmp/remoteshell.log
         wget -l inf -nH -N -r --waitretry=10 --random-wait -e robots=off -T 60 -nH  --reject "index.html*" --no-parent http://${XCATSERVER}/install/postscripts/ -P /xcatpost >> /tmp/remoteshell.log
         if [ -f /xcatpost/install/postscripts/hostkeys/authorized_keys ]; then
            cp -a /xcatpost/install/postscripts/hostkeys/authorized_keys /root/.ssh
            rm -fr /xcatpost/install
            break
         fi
         sleep 5
      done
   fi

   for ii in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
      [ -f /etc/ssh/ssh_host_rsa_key.pub -a -f /etc/ssh/ssh_host_rsa_key ] && break
      echo "Check /etc/ssh/ssh_host_rsa_key file" >> /tmp/remoteshell.log
      sleep 6
   done
   if [ ! -f /etc/ssh/ssh_host_rsa_key.pub -a ! -f /etc/ssh/ssh_host_rsa_key ]; then
      /xcatpost/remoteshell.orig >> /tmp/remoteshell.log
      exit 0
   fi

   if [ -x /usr/bin/openssl ]; then
     USEOPENSSLFORXCAT=1 #Though this is the only method going forward, flag to allow backward compatibility with 2.2 generated netboot images
     export USEOPENSSLFORXCAT
   fi
   while [ 1 ]; do
      ping -c 2 ${XCATSERVER} >& /dev/null && break
      echo "Wait ${XCATSERVER} server" >> /tmp/remoteshell.log
      sleep 5
   done
   export XCATSERVER=${XCATSERVER}:3001

   ii=0
   while [ 1 ]; do
      echo "*** Try($ii) sync files" >> /tmp/remoteshell.log
      /xcatpost/syncfiles >> /tmp/remoteshell.log
      [ -f /etc/ssh/ssh_known_hosts ] && break
      sleep 7
      ii=$(($ii+1))
   done
   sleep 3
fi

echo "
  while [ 1 ]; do
    [ -f /etc/ssh/ssh_known_hosts ] && break
    echo \"Wait /etc/ssh/ssh_known_hosts file\" >> /tmp/remoteshell.log
    sleep 6
  done
  sleep 10
  grep -e \"^${IMAGENAME}-\" -e \"^${MONSERVER} \" /etc/ssh/ssh_known_hosts > /etc/ssh/ssh_known_hosts_
  [ -s /etc/ssh/ssh_known_hosts_ ] && cp -a /etc/ssh/ssh_known_hosts_ /etc/ssh/ssh_known_hosts
  rm -f /root/.ssh/known_hosts
  touch /root/.ssh/known_hosts
  [ -d /usr/lib/systemd/system ] && systemctl restart sshd || /etc/init.d/sshd restart
  echo "Config done" >> /tmp/remoteshell.log
  rm -f /tmp/ssh_re_config
" > /tmp/ssh_re_config
chmod +x /tmp/ssh_re_config
nohup /tmp/ssh_re_config >& /dev/null &
